#!/usr/bin/env bash
# display "Holberton School" 10 times and "Hi" in the 9th time
i=1
while [ $i -le 10 ]
do
    echo "Holberton School"
    if [ $i -eq 9 ]
    then
	echo "Hi"
    fi
    i=$(( i + 1 ))
done
