#!/usr/bin/env bash
#Run Nginx as Nginx
sudo chmod -R 755 /etc/nginx/nginx.conf
sudo sed -i 's/user www-data;/user ngix;/' /etc/nginx/nginx.conf
sudo sed -i 's/80/8080/g' /etc/nginx/sites-available/default
su nginx -c "service nginx restart"
