#!/usr/bin/env bash
#Run Nginx as Nginx

sudo apt-get update
sudo apt-get -y install nginx
sudo service nginx start
sudo chmod 600 /etc/nginx/nginx.conf
sudo sed -i 's/#user www-data;/user nginx;/' /etc/nginx/nginx.conf
sudo service nginx restart
