#!/usr/bin/env bash
# runs nginx as the nginx user
sudo chmod 766 /etc/nginx/nginx.conf
sed -i 's/80/8080/g' /etc/nginx/sites-available/default
sudo pkill -o apache2
sudo -su "nginx" service nginx restart
